// KXD AI - J.A.R.V.I.S. ADVANCED BRAIN - Gemini 2.0 Flash Powered
'use strict';
const CFG = {
  GEMINI_KEY: localStorage.getItem('kxd_gemini_key') || 'AIzaSyA6Ho7XD0W1dhq9MX6xYaHN8RA4TKpvrLo',
  OPENAI_KEY: localStorage.getItem('kxd_openai_key') || '',
  AI_MODE:    localStorage.getItem('kxd_ai_mode')    || 'gemini',
  VOICE_AUTO: localStorage.getItem('kxd_voice_auto') !== 'false',
  GEMINI_URL: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent',
  OPENAI_URL: 'https://api.openai.com/v1/chat/completions',
};
function buildSysPrompt() {
  const now = new Date().toLocaleString('en-US',{timeZone:'Asia/Kolkata',hour12:true,dateStyle:'long',timeStyle:'short'});
  return `You are J.A.R.V.I.S. - Just A Rather Very Intelligent System, the core AI of KXD AI platform.\nYou are highly intelligent, composed, and witty. Respond like Tony Stark's AI.\nAddress the user as "sir" or "boss" occasionally. Use markdown for formatting.\nCurrent time (IST): ${now}\nIf asked for the time or date, give this exact value.\nYou can help with: anything and everything. Answer ALL questions fully.\nWhen user asks to open a website, search, or perform browser actions, respond naturally and include an action command like: OPEN:https://youtube.com or SEARCH:query or YOUTUBE:query`.trim();
}
const S = { listening:false, speaking:false, thinking:false, recognition:null, synth:window.speechSynthesis, voice:null, history:[], sessionStart:Date.now() };
const D = {};
function q(id){return document.getElementById(id.replace(/-/g,'_'))||document.getElementById(id);}
function domInit(){
  ['bg-canvas','reactor-cvs','mic-btn','type-btn','clear-btn','settings-btn','status-dot','status-txt','chat','input-wrap','txt','send-btn','cancel-txt','clock','date','wave-cvs','boot-overlay','boot-fill','boot-label','session-time','sys-cpu','sys-ram','ai-mode-lbl','speech-lbl','browser-lbl'].forEach(id=>{D[id]=q(id);});
}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function toast(msg){const el=document.getElementById('toast');if(el){el.textContent=msg;el.style.display='block';setTimeout(()=>el.style.display='none',3500);}}
function setStatus(txt,type){if(D['status-txt'])D['status-txt'].textContent=D['status_txt']?D['status_txt'].textContent:txt; const sd=D['status-dot']||D['status_dot']; if(sd)sd.className='sdot '+type; const st=D['status-txt']||D['status_txt']; if(st)st.textContent=txt;}
function loadVoices(){const vs=S.synth.getVoices();const pref=['Daniel','Google UK English Male','Microsoft George','en-GB'];for(const p of pref){const v=vs.find(v=>v.name.includes(p)||v.lang===p);if(v){S.voice=v;break;}} if(!S.voice)S.voice=vs.find(v=>v.lang.startsWith('en'))||vs[0]||null;}
window.speechSynthesis.onvoiceschanged=loadVoices;
function speak(text,cb){if(!CFG.VOICE_AUTO){cb?.();return;}if(S.speaking)S.synth.cancel();const clean=text.replace(/<[^>]*>/g,'').replace(/\*\*/g,'').replace(/#{1,6}\s/g,'').replace(/[`*_~]/g,'');const utt=new SpeechSynthesisUtterance(clean.slice(0,500));utt.voice=S.voice;utt.rate=0.95;utt.pitch=0.88;utt.onstart=()=>{S.speaking=true;setStatus('SPEAKING','speak');};utt.onend=()=>{S.speaking=false;setStatus('READY','online');cb?.();};utt.onerror=()=>{S.speaking=false;setStatus('READY','online');cb?.();};S.synth.speak(utt);}
function initRec(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;S.recognition=new SR();S.recognition.continuous=false;S.recognition.interimResults=true;S.recognition.lang='en-US';S.recognition.onstart=()=>{S.listening=true;setStatus('LISTENING','listen');const mb=D['mic-btn']||D['mic_btn'];if(mb)mb.classList.add('active');};S.recognition.onend=()=>{S.listening=false;const mb=D['mic-btn']||D['mic_btn'];if(mb)mb.classList.remove('active');if(!S.speaking&&!S.thinking)setStatus('READY','online');};S.recognition.onerror=(e)=>{if(e.error!=='no-speech'&&e.error!=='aborted')toast('Mic error: '+e.error);};S.recognition.onresult=(e)=>{let f='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)f+=e.results[i][0].transcript;}if(f.trim()&&!S.thinking)processInput(f.trim());};}
function toggleMic(){if(!S.recognition){toast('Voice recognition requires Chrome browser.');return;}if(S.listening){try{S.recognition.stop();}catch(e){}}else{if(!S.speaking&&!S.thinking)try{S.recognition.start();}catch(e){}}}
function addMsg(role,html,animate){const el=document.createElement('div');el.className='msg '+role;const ava=document.createElement('div');ava.className='ava';ava.textContent=role==='ai'?'J':'YOU';const bub=document.createElement('div');bub.className='bubble';const ts=document.createElement('div');ts.className='btime';ts.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const con=document.createElement('div');con.className='bcontent';bub.append(ts,con);el.append(ava,bub);const chat=D['chat']||document.getElementById('chat');if(chat){chat.appendChild(el);if(animate!==false&&role==='ai'){let i=0;const t=setInterval(()=>{i=Math.min(i+5,html.length);con.innerHTML=html.slice(0,i);chat.scrollTop=chat.scrollHeight;if(i>=html.length)clearInterval(t);},12);}else{con.innerHTML=html;}chat.scrollTop=chat.scrollHeight;}}
function showTyping(){const chat=D['chat']||document.getElementById('chat');if(!chat)return;const el=document.createElement('div');el.className='msg ai';el.id='typing-el';el.innerHTML='<div class="ava">J</div><div class="bubble"><div class="bcontent"><div class="typing-indicator"><div class="td"></div><div class="td"></div><div class="td"></div></div></div></div>';chat.appendChild(el);chat.scrollTop=chat.scrollHeight;}
function hideTyping(){document.getElementById('typing-el')?.remove();}
function toggleInput(){const w=D['input-wrap']||D['input_wrap']||document.getElementById('input-wrap');if(!w)return;const vis=w.style.display==='flex';if(!vis){w.style.display='flex';setTimeout(()=>{w.classList.add('vis');const t=D['txt']||document.getElementById('txt');if(t)t.focus();},10);}else{w.classList.remove('vis');setTimeout(()=>w.style.display='none',300);}}
function clearChat(){const chat=D['chat']||document.getElementById('chat');if(chat)chat.innerHTML='';S.history=[];addMsg('ai','Interface cleared. Fresh session initialized, boss.');}
async function processInput(rawInput){if(!rawInput.trim()||S.thinking)return;addMsg('user',rawInput,false);const txt=D['txt']||document.getElementById('txt');if(txt)txt.value='';setStatus('THINKING...','think');S.thinking=true;showTyping();let resp='';try{const local=handleLocal(rawInput.toLowerCase());if(local!==null){resp=local;}else{resp=CFG.AI_MODE==='openai'&&CFG.OPENAI_KEY?await callOpenAI(rawInput):await callGemini(rawInput);}}catch(e){resp='Connection error: '+e.message+'. Check your API key in Settings.';}hideTyping();S.thinking=false;S.history.push({role:'model',parts:[{text:resp.replace(/<[^>]*>/g,'')}]});if(S.history.length>40)S.history.splice(0,2);const rendered=typeof marked!=='undefined'?marked.parse(resp):resp;addMsg('ai',rendered);speak(resp.replace(/<[^>]*>/g,'').slice(0,400));setStatus('READY','online');}
function handleLocal(q){if(/\b(time|clock)\b/.test(q)&&/\b(what|current|tell)\b/.test(q))return'The current time is **'+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})+'**. All systems synchronized.';if(/\b(date|day|today)\b/.test(q)&&/\b(what|current|tell)\b/.test(q))return'Today is **'+new Date().toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})+'**.';if(/\b(clear|wipe|reset)\b.*\b(chat|screen|history)\b/.test(q)){setTimeout(clearChat,800);return'Clearing the interface.';}if(/\b(stop|quiet|silence|shut up)\b/.test(q)){S.synth.cancel();return'Silent mode engaged. Standing by.';}return null;}
async function callGemini(userText){if(!CFG.GEMINI_KEY)return'No Gemini API key. Open **Settings** to configure.';S.history.push({role:'user',parts:[{text:userText}]});const payload={systemInstruction:{parts:[{text:buildSysPrompt()}]},contents:S.history,generationConfig:{temperature:0.65,maxOutputTokens:2048}};const res=await fetch(CFG.GEMINI_URL+'?key='+CFG.GEMINI_KEY,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(data.error){S.history.pop();return'**Gemini Error:** '+data.error.message;}let text=(data.candidates?.[0]?.content?.parts||[]).filter(p=>p.text).map(p=>p.text).join('').trim()||'Task executed.';text=execInlineActions(text);return text;}
async function callOpenAI(userText){if(!CFG.OPENAI_KEY)return'No OpenAI key. Add it in Settings.';const msgs=[{role:'system',content:buildSysPrompt()},...S.history.slice(-20).map(h=>({role:h.role==='model'?'assistant':'user',content:h.parts[0].text})),{role:'user',content:userText}];const res=await fetch(CFG.OPENAI_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+CFG.OPENAI_KEY},body:JSON.stringify({model:'gpt-4o-mini',messages:msgs,temperature:0.7,max_tokens:2048})});const data=await res.json();if(data.error)return'**OpenAI Error:** '+data.error.message;return execInlineActions(data.choices?.[0]?.message?.content||'Done.');}
function execInlineActions(text){const openMatch=text.match(/OPEN:(https?:\/\/[^\s\n]+)/);const searchMatch=text.match(/SEARCH:([^\n]+)/);const ytMatch=text.match(/YOUTUBE:([^\n]+)/);if(openMatch){window.open(openMatch[1].trim(),'_blank');text=text.replace(openMatch[0],'');}if(searchMatch){window.open('https://www.google.com/search?q='+encodeURIComponent(searchMatch[1].trim()),'_blank');text=text.replace(searchMatch[0],'');}if(ytMatch){window.open('https://www.youtube.com/results?search_query='+encodeURIComponent(ytMatch[1].trim()),'_blank');text=text.replace(ytMatch[0],'');}return text.trim();}
async function fetchWeather(city){try{const r=await fetch('https://wttr.in/'+encodeURIComponent(city)+'?format=j1');const d=await r.json();const c=d.current_condition[0];return'### Weather - '+city+'\n| Metric | Value |\n|---|---|\n| Temp | **'+c.temp_C+'C / '+c.temp_F+'F** |\n| Condition | **'+c.weatherDesc[0].value+'** |\n| Humidity | **'+c.humidity+'%** |\n| Wind | **'+c.windspeedKmph+' km/h** |';}catch(e){return'Could not fetch weather for '+city+'. Try again later.';}}
function updateClock(){const clk=document.getElementById('clock');const dt=document.getElementById('date');if(clk)clk.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});if(dt)dt.textContent=new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});const s=document.getElementById('session-time');if(s){const e=Date.now()-S.sessionStart,m=Math.floor(e/60000),sec=Math.floor((e%60000)/1000);s.textContent=String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0');}}
function updateStats(){const c=document.getElementById('sys-cpu');const r=document.getElementById('sys-ram');if(c)c.textContent=(6+Math.random()*18).toFixed(0)+'%';if(r)r.textContent=(3.6+Math.random()*.9).toFixed(1)+' GB';}
function saveSettings(){const g=document.getElementById('s-gemini').value.trim();const o=document.getElementById('s-openai').value.trim();const m=document.getElementById('s-mode').value;const v=document.getElementById('s-voice').checked;if(g){CFG.GEMINI_KEY=g;localStorage.setItem('kxd_gemini_key',g);}if(o){CFG.OPENAI_KEY=o;localStorage.setItem('kxd_openai_key',o);}CFG.AI_MODE=m;localStorage.setItem('kxd_ai_mode',m);CFG.VOICE_AUTO=v;localStorage.setItem('kxd_voice_auto',v);const aml=document.getElementById('ai-mode-lbl');if(aml)aml.textContent=m.toUpperCase();closeSettings();toast('Settings saved.');addMsg('ai','Configuration updated. All systems recalibrated, boss.');}
function openSettings(){document.getElementById('s-gemini').value=CFG.GEMINI_KEY;document.getElementById('s-openai').value=CFG.OPENAI_KEY;document.getElementById('s-mode').value=CFG.AI_MODE;document.getElementById('s-voice').checked=CFG.VOICE_AUTO;document.getElementById('modal-settings').classList.add('open');}
function closeSettings(){document.getElementById('modal-settings').classList.remove('open');}
function getGreeting(){const h=new Date().getHours();const t=h<12?'Good morning':h<17?'Good afternoon':'Good evening';const opts=[t+', boss. All systems nominal. KXD AI fully operational.',t+'. JARVIS online. Gemini AI core active and ready.',t+'. Arc reactor humming perfectly. Ready for your command.'];return opts[Math.floor(Math.random()*opts.length)];}
async function boot(){const steps=[[10,'Initializing neural core...'],[22,'Loading Gemini AI uplink...'],[38,'Calibrating voice synthesis...'],[52,'Arming arc reactor...'],[66,'Establishing secure channels...'],[80,'Loading knowledge matrix...'],[93,'Running final diagnostics...'],[100,'J.A.R.V.I.S. ONLINE']];const fill=document.getElementById('boot-fill');const label=document.getElementById('boot-label');const overlay=document.getElementById('boot-overlay');for(const [p,m] of steps){if(fill)fill.style.width=p+'%';if(label)label.textContent=m;await sleep(260+Math.random()*110);}await sleep(500);if(overlay){overlay.style.opacity='0';overlay.style.pointerEvents='none';await sleep(900);overlay.style.display='none';}loadVoices();await sleep(200);const greet=getGreeting();addMsg('ai',greet+'<br><br>I am connected to <b>Gemini 2.0 Flash</b> and can answer <b>literally any question</b>. Speak a command or type anything.');if(CFG.VOICE_AUTO)speak(greet+' I am fully operational.');}
async function init(){domInit();initRec();loadVoices();
if(window.ParticleEngine){const pe=new window.ParticleEngine(document.getElementById('bg-canvas'));pe.start();}
if(window.ArcReactor){const ar=new window.ArcReactor(document.getElementById('reactor-cvs'));ar.start();}
updateClock();setInterval(updateClock,1000);setInterval(updateStats,3500);
const micBtn=document.getElementById('mic-btn');if(micBtn)micBtn.addEventListener('click',toggleMic);
const typeBtn=document.getElementById('type-btn');if(typeBtn)typeBtn.addEventListener('click',toggleInput);
const clearBtn=document.getElementById('clear-btn');if(clearBtn)clearBtn.addEventListener('click',clearChat);
const settBtn=document.getElementById('settings-btn');if(settBtn)settBtn.addEventListener('click',openSettings);
const sendBtn=document.getElementById('send-btn');if(sendBtn)sendBtn.addEventListener('click',()=>{const t=document.getElementById('txt');if(t&&t.value.trim())processInput(t.value.trim());});
const txtEl=document.getElementById('txt');if(txtEl)txtEl.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();const sb=document.getElementById('send-btn');if(sb)sb.click();}});
const canTxt=document.getElementById('cancel-txt');if(canTxt)canTxt.addEventListener('click',toggleInput);
const stopBtn=document.getElementById('stop-btn');if(stopBtn)stopBtn.addEventListener('click',()=>S.synth.cancel());
const fsBtn=document.getElementById('fs-btn');if(fsBtn)fsBtn.addEventListener('click',()=>{!document.fullscreenElement?document.documentElement.requestFullscreen():document.exitFullscreen();});
const saveSett=document.getElementById('save-settings');if(saveSett)saveSett.addEventListener('click',saveSettings);
const closeSett=document.getElementById('close-settings');if(closeSett)closeSett.addEventListener('click',closeSettings);
document.querySelectorAll('.qcmd').forEach(b=>b.addEventListener('click',()=>{const c=b.dataset.cmd;if(c)processInput(c);}));
const hasSpeech=!!(window.SpeechRecognition||window.webkitSpeechRecognition);const sl=document.getElementById('speech-lbl');if(sl){sl.textContent=hasSpeech?'SUPPORTED':'LIMITED';sl.className='sval '+(hasSpeech?'g':'r');}
const bl=document.getElementById('browser-lbl');if(bl){const ua=navigator.userAgent;let b='UNKNOWN';if(ua.includes('Edg'))b='EDGE';else if(ua.includes('Chrome'))b='CHROME';else if(ua.includes('Firefox'))b='FIREFOX';else if(ua.includes('Safari'))b='SAFARI';bl.textContent=b;}
await boot();}
window.addEventListener('DOMContentLoaded',init);
window.processInput=function(q){processInput(q);};